# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='ordem',
            field=models.IntegerField(default=1),
        ),
    ]
