# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_tema_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ('ordem', 'nome')},
        ),
        migrations.AddField(
            model_name='fonte',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
