# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160828_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidade',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
