# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_localidade_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='indicador',
            name='formato',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='indicador',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='periodo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='localidade',
            name='tipo',
            field=models.CharField(choices=[('estado', 'Estado'), ('regiao', 'Regi\xe3o'), ('municipio', 'Munic\xedpio')], max_length=60),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
