# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160828_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=False)),
                ('icone', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('titulo', models.CharField(max_length=250)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('css_class', models.TextField(default='col-lg-12')),
                ('periodos', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Dashboard')),
                ('indicadores', models.ManyToManyField(to='data.Indicador')),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='dashboard',
            field=models.BooleanField(default=False, verbose_name='Exibir no menu de dashboards?'),
        ),
        migrations.AlterField(
            model_name='localidade',
            name='tipo',
            field=models.CharField(choices=[('uf', 'Estado de S\xe3o Paulo'), ('regsau', 'Regi\xf5es de Sa\xfade'), ('drs', 'Departamentos Regionais de Sa\xfade'), ('rras', 'Redes Regionais de Aten\xe7\xe3o \xe0 Sa\xfade'), ('munic', 'Munic\xedpios Paulistas')], max_length=60),
        ),
        migrations.AlterField(
            model_name='tema',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='painel',
            name='localidades',
            field=models.ManyToManyField(to='data.Localidade'),
        ),
        migrations.AddField(
            model_name='painel',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Modelo'),
        ),
    ]
