# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20161009_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('nome', models.CharField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='indicador',
            name='formato',
            field=models.CharField(blank=True, default='', help_text='Por exemplo: %0.3f formata com 3 casas depois da v\xedrgula.', max_length=50),
        ),
    ]
