# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20161022_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Categoria'),
        ),
    ]
