# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_categoria_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='home',
            field=models.BooleanField(default=True, verbose_name='Exibir card na homepage?'),
        ),
    ]
