# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_categoria_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='menu',
            field=models.BooleanField(default=True, verbose_name='Exibir entrada no menu'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='home',
            field=models.BooleanField(default=True, verbose_name='Exibir card na homepage'),
        ),
    ]
