# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
