# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('corpo', models.TextField()),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('ordem',), 'verbose_name': '\xcdtem de menu', 'verbose_name_plural': '\xcdtens de menu'},
        ),
    ]
