# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_conteudo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='css',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
