# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_conteudo_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoRodape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown')], default='html', max_length=30)),
                ('css', models.CharField(blank=True, max_length=100, null=True)),
                ('corpo', models.TextField()),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
    ]
